name: dropbox-client
version: '61.4.95'
summary: The Dropbox Client for Linux
description: Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter. Sync your files across computers and to the web.
icon: dropbox.png
grade: devel
confinement: devmode

apps:
  dropbox-client:
    command: bin/dropbox

parts:
  dropbox:
    build-packages:
      - pkgconf
      - libnautilus-extension-dev
      - python-zbarpygtk
      - python-docutils
    source: https://linux.dropbox.com/packages/nautilus-dropbox-2018.11.08.tar.bz2
    plugin: autotools

  python2:
    after: [dropbox]
    source: https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz
    plugin: autotools

  pygtk:
#    build-packages:
#      - libglib2.0-dev
#      - libgtk2.0-dev
#      - python-dev
#      - python-gobject-2-dev
#      - python-gtk2
#      - python-gtk2-doc
    after: [python2]
#    source: http://deb.debian.org/debian/pool/main/p/pygtk/pygtk_2.24.0.orig.tar.gz
#    plugin: autotools
#    configflags: ["--prefix=/bin/python"]
    override-build:
      apt install python-gtk2-dev -y
