name: dropbox-client
version: '61.4.95'
summary: The Dropbox Client for Linux
description: Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter. Sync your files across computers and to the web.
icon: dropbox.png
grade: devel
confinement: devmode

apps:
  dropbox-client:
    command: bin/dropbox

parts:
  dropbox:
    build-packages:
      - pkgconf
      - libnautilus-extension-dev
      - python-zbarpygtk
      - python-docutils
    source: https://linux.dropbox.com/packages/nautilus-dropbox-2018.11.08.tar.bz2
    plugin: autotools
    stage-packages:
      - python-gtk2-dev
      - python2.7
