name: dropbox-client
version: '2019.02.14'
summary: The Dropbox Client for Linux
description: Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter. Sync your files across computers and to the web.
icon: dropbox.png
grade: devel
confinement: strict

apps:
  dropbox-client:
    command: dropbox
    plugs:
      - home
      - network
      - browser-support
      - desktop
      - desktop-legacy
      - wayland

parts:
  dropbox:
    build-packages:
      - libpango1.0-0
      - libpangox-1.0-0
    source: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb
    source-type: deb
    plugin: dump
    stage-packages:
      - python-gtk2-dev
      - python-gtk2
      - python2.7
      - libpango1.0-0
      - libpangox-1.0-0
      - python-gpgme
      - libgdk-pixbuf2.0-0
      - gir1.2-gdkpixbuf-2.0
      - libgdk-pixbuf2.0-common
      - libgdk-pixbuf2.0-dev
      - libatk1.0-0
      - procps
      - libcairo2
      - libglib2.0-0
      - libgtk2.0-0
      - python3-gi
