name: dropbox-client
version: '61.4.95'
summary: The Dropbox Client for Linux
description: Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter. Sync your files across computers and to the web.
grade: devel
confinement: devmode

apps:
  dropbox-client:
    command: bin/dropbox
    desktop: dropbox-client.desktop $SNAP/share/applications/dropbox-client.desktop

parts:
  python2:
    after: [dropbox]
    source: https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz
    plugin: autotools

  dropbox:
    build-packages:
      - pkgconf
      - libnautilus-extension-dev
      - python-zbarpygtk
      - python-docutils
    source: https://linux.dropbox.com/packages/nautilus-dropbox-2018.11.08.tar.bz2
    plugin: autotools
