name: dropbox-client
version: '61.4.95'
summary: The Dropbox Client for Linux
description: Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter. Sync your files across computers and to the web.
icon: dropbox.png
grade: devel
confinement: devmode

architectures:
  - build-on: amd64

apps:
  dropbox-client:
    command: dropbox
    plugs:
      - home
      - network
      - network-bind
      - browser-support
      - desktop
      - desktop-legacy
      - wayland

parts:
  dropbox:
    build-packages:
      - libpango1.0-0
      - libpangox-1.0-0
    source: https://linux.dropbox.com/packages/ubuntu/dropbox_2018.11.08_amd64.deb
    source-type: deb
    plugin: dump
    stage-packages:
      - python-gtk2-dev
      - python2.7
      - libpango1.0-0
      - libpangox-1.0-0
      - python-gpgme
      - libgdk-pixbuf2.0-0
      - gir1.2-gdkpixbuf-2.0
      - libgdk-pixbuf2.0-common
      - libgdk-pixbuf2.0-dev
