name: dropbox-client
version: '61.4.95'
summary: The Dropbox Client for Linux
description: Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter. Sync your files across computers and to the web.
icon: dropbox.png
core: core18
grade: devel
confinement: devmode

apps:
  dropbox-client:
    command: bin/dropbox
    plugs:
      - home
      - network

parts:
  dropbox:
    source: https://linux.dropbox.com/packages/ubuntu/dropbox_2018.11.08_amd64.deb
    source-type: deb
    plugin: dump
    stage-packages:
      - python-gtk2-dev
      - python2.7
